import express from 'express';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import crypto from 'crypto';
import QRCode from 'qrcode';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const app=express();app.disable('x-powered-by');app.set('trust proxy',1);app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:'1mb'}));app.use(express.urlencoded({extended:false,limit:'1mb'}));
const NODE_ENV=process.env.NODE_ENV||'development',PORT=Number(process.env.PORT||3000),VERSION=process.env.APP_VERSION||'1.2.0',SERVICE='qrv-platform',APP_ORIGIN=(process.env.QRV_PLATFORM_ORIGIN||'https://qrv.network').replace(/\/$/,''),API_BASE_URL=(process.env.QRV_API_BASE_URL||'https://api.qrv.network/api/v1').replace(/\/$/,''),API_ORIGIN=API_BASE_URL.replace(/\/api\/v1$/,''),API_WRITE_KEY=process.env.QRV_PLATFORM_API_KEY||process.env.QRV_API_KEY||'',SESSION_SECRET=process.env.SESSION_SECRET||'',ISSUER_ACCESS_CODE=process.env.ISSUER_ACCESS_CODE||'',SESSION_COOKIE='qrv_issuer_session',SESSION_TTL_MS=Number(process.env.SESSION_TTL_MS||43200000),STARTED_AT=new Date().toISOString();
const __dirname=path.dirname(fileURLToPath(import.meta.url)),WEB_DIST=path.join(__dirname,'dist'),WEB_INDEX=path.join(WEB_DIST,'index.html');
app.use('/assets',express.static(path.join(WEB_DIST,'assets'),{immutable:NODE_ENV==='production',maxAge:NODE_ENV==='production'?'1y':0,index:false}));
app.use(rateLimit({windowMs:60000,max:240,standardHeaders:true,legacyHeaders:false}));
const legacyHostRoutes={'verify.qrv.network':'/verify','issuer.qrv.network':'/issuer','registry.qrv.network':'/registry','explorer.qrv.network':'/explorer','docs.qrv.network':'/docs','developers.qrv.network':'/developers','status.qrv.network':'/status','store.qrv.network':'/store','wallet.qrv.network':'/wallet','admin.qrv.network':'/admin'};
app.use((req,res,next)=>{const host=String(req.hostname||'').toLowerCase();if(host==='www.qrv.network')return res.redirect(308,`${APP_ORIGIN}${req.originalUrl}`);const prefix=legacyHostRoutes[host];if(!prefix)return next();const suffix=req.originalUrl==='/'?'':req.originalUrl;return res.redirect(308,`${APP_ORIGIN}${prefix}${suffix}`);});
const escapeHtml=(v='')=>String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
function parseCookies(req){const c={};for(const p of String(req.headers.cookie||'').split(';')){const[k,...r]=p.trim().split('=');if(k)c[k]=decodeURIComponent(r.join('='));}return c;}
const sign=v=>SESSION_SECRET?crypto.createHmac('sha256',SESSION_SECRET).update(v).digest('base64url'):'';
function createSessionToken(){const p=Buffer.from(JSON.stringify({role:'issuer',exp:Date.now()+SESSION_TTL_MS})).toString('base64url');return`${p}.${sign(p)}`;}
function safeEqual(l,r){const a=Buffer.from(String(l||'')),b=Buffer.from(String(r||''));return a.length===b.length&&a.length>0&&crypto.timingSafeEqual(a,b);}
function validSession(req){if(!SESSION_SECRET)return false;const t=parseCookies(req)[SESSION_COOKIE];if(!t||!t.includes('.'))return false;const[p,s]=t.split('.');if(!safeEqual(s,sign(p)))return false;try{const d=JSON.parse(Buffer.from(p,'base64url').toString('utf8'));return d.role==='issuer'&&Number(d.exp)>Date.now();}catch{return false;}}
const requireIssuer=(req,res,next)=>validSession(req)?next():res.redirect(303,'/issuer');
async function api(path,options={}){const headers={accept:'application/json',...(options.headers||{})};if(options.write){if(!API_WRITE_KEY)throw new Error('QRV_PLATFORM_API_KEY is not configured');headers['x-api-key']=API_WRITE_KEY;}if(options.body&&!headers['content-type'])headers['content-type']='application/json';const response=await fetch(`${API_BASE_URL}${path}`,{...options,headers,body:options.body&&typeof options.body!=='string'?JSON.stringify(options.body):options.body});const payload=await response.json().catch(()=>({}));return{response,payload};}
async function apiRoot(path){const response=await fetch(`${API_ORIGIN}${path}`,{headers:{accept:'application/json'}});const payload=await response.json().catch(()=>({}));return{response,payload};}
const nav=[['Protocol','/protocol'],['How It Works','/how-it-works'],['Verify','/verify'],['Registry','/registry'],['Use Cases','/use-cases'],['Developers','/developers'],['Pricing','/pricing'],['About','/about']];
const css=`:root{--bg:#030712;--panel:#081426;--line:rgba(96,165,250,.2);--text:#f5f9ff;--muted:#b7c7e2;--gold:#f2d06b}*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,sans-serif;background:linear-gradient(180deg,#06101e,#020617);color:var(--text);min-height:100vh}.wrap{max-width:1180px;margin:auto;padding:22px}.topbar{display:flex;justify-content:space-between;gap:16px;padding:14px;border:1px solid var(--line);border-radius:18px}.nav{display:flex;gap:8px;flex-wrap:wrap}.nav a,.brand{color:inherit;text-decoration:none;font-weight:800}.hero,.section{padding:64px 0 28px}.hero h1,.section h1{font-size:clamp(38px,6vw,70px);line-height:1.03}.lead,p,li{color:var(--muted);font-size:18px;line-height:1.6}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.card{border:1px solid var(--line);background:#081426;border-radius:20px;padding:22px}.actions{display:flex;gap:12px;flex-wrap:wrap;margin:24px 0}.btn,button{padding:12px 18px;border-radius:999px;border:0;background:var(--gold);color:#07111f;font-weight:900;text-decoration:none}.btn.alt{background:transparent;color:white;border:1px solid var(--line)}form.stack{display:grid;gap:12px}input,select,textarea{padding:13px;border-radius:12px;border:1px solid #36507d;background:#071426;color:white}.table{width:100%;border-collapse:collapse}.table td,.table th{padding:11px;border-bottom:1px solid var(--line);text-align:left}.mono{font-family:monospace;word-break:break-all}.status{font-weight:900}.VERIFIED{color:#86efac}.REVOKED,.NOT_FOUND,.UNAVAILABLE{color:#fca5a5}.EXPIRED{color:#fcd34d}.footer{margin-top:50px;padding:28px 0;border-top:1px solid var(--line)}@media(max-width:850px){.topbar{flex-direction:column}.grid{grid-template-columns:1fr}}`;
function shell(title,description,body){return`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)}</title><meta name="description" content="${escapeHtml(description)}"><style>${css}</style></head><body><div class="wrap"><header class="topbar"><a class="brand" href="/">QR-V™ NETWORK</a><nav class="nav">${nav.map(([l,h])=>`<a href="${h}">${l}</a>`).join('')}<a href="/issuer">Issuer</a><a href="/status">Status</a></nav></header>${body}<footer class="footer">QR-V™ Global Verification Network • QRVP-1 • QVS-1.0 • Platform ${VERSION}</footer></div></body></html>`;}
function page({eyebrow,title,lead,cards=[],actions=[]}){return shell(title,lead,`<main><section class="hero"><strong>${escapeHtml(eyebrow)}</strong><h1>${escapeHtml(title)}</h1><p class="lead">${escapeHtml(lead)}</p><div class="actions">${actions.map(([l,h,a])=>`<a class="btn${a?' alt':''}" href="${h}">${escapeHtml(l)}</a>`).join('')}</div></section><section class="grid">${cards.map(([h,t,u])=>`<article class="card"><h2>${escapeHtml(h)}</h2><p>${escapeHtml(t)}</p>${u?`<a href="${u}">Open →</a>`:''}</article>`).join('')}</section></main>`);}
const pages={
'/protocol':['Protocol','QRVP-1','Identifier, resolution, registry lookup, validation, lifecycle status and verification responses.'],
'/how-it-works':['Workflow','Issue → Scan → Verify','Issuers create canonical records; users scan QR-V links; the API returns deterministic lifecycle state.'],
'/use-cases':['Solutions','Verification for records that matter','Certificates, memberships, products, documents, assets and property records.'],
'/about':['Company','About QR-V','Verification infrastructure and protocol layer operated as a ONEGODIAN, LLC product.'],
'/standards':['Standard','QVS-1.0','Operational verification rules for deterministic registry-backed QR-V records.'],
'/security':['Security','Secure by default','The browser platform is separated from the API, datastore and privileged secrets.'],
'/developers':['Developers','Build on QR-V','Canonical API: https://api.qrv.network/api/v1.'],
'/pricing':['Commercial','Issuer pricing','Implementation and recurring issuer plans support certificate and enterprise verification workflows.'],
'/store':['Store','QR-V products and services','Commercial onboarding and implementation packages live on the canonical platform.'],
'/enterprise':['Enterprise','Institutional verification infrastructure','Issuer onboarding, imports, API integration, audit reporting and white-label deployments.'],
'/certificate-verification':['Certificates','Verified Certificates','The first commercial lifecycle: issue, verify, expire or revoke.'],
'/docs':['Documentation','QR-V documentation','Protocol, standard, architecture, verification, issuer and API documentation.'],
'/docs/overview':['Docs','System Overview','qrv.network is the public platform; api.qrv.network is the trusted backend.'],
'/docs/protocol':['Docs','QRVP-1','Canonical verification URLs use qrv.network/verify/{QRVID}.'],
'/docs/verification':['Docs','Verification','Current public states: VERIFIED, REVOKED, EXPIRED and NOT_FOUND.'],
'/docs/registry':['Docs','Registry','Canonical registry persistence remains private behind api.qrv.network.'],
'/docs/issuers':['Docs','Issuers','Issue and manage QR-V records through qrv.network/issuer.'],
'/docs/developers':['Docs','Developers','External systems integrate with api.qrv.network.'],
'/docs/api-reference':['Docs','API Reference','Canonical API base: https://api.qrv.network/api/v1.'],
'/network':['Network','QR-V Global Verification Network','One public platform node and one trusted API/data node form the canonical production network.'],
'/billing':['Billing','Billing & Entitlements','Commercial entitlement enforcement belongs behind the trusted backend. Payment-provider secrets are never exposed here.'],
'/wallet':['Wallet','QR-V Wallet','Reserved platform module for user-held verification references and credentials. No financial custody is implied.'],
'/admin':['Administration','QR-V Administration','Private operational administration is being consolidated under the platform while privileged operations remain API-authorized.']};
const homePage=()=>page({eyebrow:'QR-V™ Global Verification Network',title:'Verify records before relying on them.',lead:'Registry-backed verification infrastructure with one public platform and one trusted API/data boundary.',actions:[['Verify a Record','/verify'],['Become an Issuer','/issuer',true]],cards:[['Verified Certificates','Issue credentials with public verification.','/certificate-verification'],['Issuer Portal','Create and manage QR-V records.','/issuer'],['Developer API','Integrate verification into external systems.','/developers']]});
app.get('/',(_q,r)=>fs.existsSync(WEB_INDEX)?r.sendFile(WEB_INDEX):r.send(homePage()));
for(const[path,d]of Object.entries(pages))app.get(path,(_q,r)=>r.send(page({eyebrow:d[0],title:d[1],lead:d[2]})));
app.get('/issuer/login',(_q,r)=>r.redirect(303,'/issuer'));
app.get('/verify',(_q,r)=>r.send(shell('Verify','Public verification',`<main class="section"><h1>Verify a QR-V record</h1><form class="stack" onsubmit="event.preventDefault();const v=document.getElementById('v').value.trim();if(v)location.href='/verify/'+encodeURIComponent(v)"><input id="v" required placeholder="QRV-CERT-..."><button>Verify</button></form></main>`)));
app.get('/verify/:qrvid',async(req,res)=>{const q=String(req.params.qrvid||'').trim().toUpperCase();try{const{response,payload}=await api(`/verify/${encodeURIComponent(q)}`);const state=String(payload.state||payload.status||(response.status===404?'NOT_FOUND':'UNAVAILABLE')).toUpperCase();const record=payload.record||payload;res.status(response.status===404?404:200).send(shell(`${state} • ${q}`,'QR-V verification result',`<main class="section"><h1>${state}</h1><p class="status ${state}">${state}</p><section class="card"><p class="mono">${escapeHtml(q)}</p><p>Issuer: ${escapeHtml(record.issuer||'')}</p><p>Type: ${escapeHtml(record.recordType||'')}</p><p>Owner: ${escapeHtml(record.owner||record.recipient||'')}</p><p>Title: ${escapeHtml(record.title||'')}</p><p class="mono">${escapeHtml(record.hash||'')}</p></section></main>`));}catch(e){res.status(503).send(page({eyebrow:'Verification',title:'Verification temporarily unavailable',lead:'The canonical API could not be reached. No verification state was asserted.'}));}});
app.get('/registry',(_q,r)=>r.send(page({eyebrow:'Registry',title:'Public Registry Lookup',lead:'Use a QRVID to inspect the public-safe canonical record.',actions:[['Verify','/verify']]})));
app.get('/registry/:qrvid',async(req,res)=>{const q=String(req.params.qrvid||'').trim().toUpperCase();try{const{response,payload}=await api(`/records/${encodeURIComponent(q)}`);if(!response.ok)return res.status(response.status).send(page({eyebrow:'Registry',title:'Record not found',lead:q}));res.send(shell(`Registry • ${q}`,'Registry record',`<main class="section"><h1>${escapeHtml(q)}</h1><pre class="card mono">${escapeHtml(JSON.stringify(payload.record||{},null,2))}</pre></main>`));}catch(e){res.status(503).send(page({eyebrow:'Registry',title:'Registry unavailable',lead:e.message}));}});
app.get('/explorer',(_q,r)=>r.redirect(308,'/registry'));app.get('/explorer/:qrvid',(req,r)=>r.redirect(308,`/registry/${encodeURIComponent(req.params.qrvid)}`));
app.get('/api-reference',(_q,r)=>r.send(page({eyebrow:'API',title:'QR-V API Reference',lead:'Use https://api.qrv.network/api/v1 for new integrations. qrv.network/api/v1 remains a compatibility path.'})));
app.get('/status',async(_q,r)=>{let h={},ready={};try{h=(await apiRoot('/healthz')).payload;}catch{}try{ready=(await apiRoot('/readyz')).payload;}catch{}r.send(page({eyebrow:'Status',title:'Two-node production status',lead:`Platform operational. API ${h.ok?'operational':'unavailable'}. Registry ${ready.ready?'ready':'not ready'}.`}));});
app.get('/issuer',(req,res)=>{if(validSession(req))return res.redirect(303,'/issuer/dashboard');const configured=Boolean(SESSION_SECRET&&ISSUER_ACCESS_CODE&&API_WRITE_KEY);res.status(configured?200:503).send(shell('Issuer Portal','Issuer access',`<main class="section"><h1>QR-V Issuer Portal</h1>${configured?`<form class="stack" method="post" action="/issuer/login"><input type="password" name="accessCode" required><button>Sign In</button></form>`:'<p>Issuer access is fail-closed until production secrets are configured.</p>'}</main>`));});
app.post('/issuer/login',(req,res)=>{if(!SESSION_SECRET||!ISSUER_ACCESS_CODE||!API_WRITE_KEY)return res.status(503).send('Issuer access not configured');if(!safeEqual(req.body?.accessCode,ISSUER_ACCESS_CODE))return res.status(401).send('Access denied');const token=createSessionToken();res.setHeader('Set-Cookie',`${SESSION_COOKIE}=${encodeURIComponent(token)}; Path=/issuer; HttpOnly; SameSite=Strict; Max-Age=${Math.floor(SESSION_TTL_MS/1000)}${NODE_ENV==='production'?'; Secure':''}`);res.redirect(303,'/issuer/dashboard');});
app.post('/issuer/logout',(_q,r)=>{r.setHeader('Set-Cookie',`${SESSION_COOKIE}=; Path=/issuer; HttpOnly; SameSite=Strict; Max-Age=0${NODE_ENV==='production'?'; Secure':''}`);r.redirect(303,'/issuer');});
app.get('/issuer/dashboard',requireIssuer,async(_q,res)=>{let records=[];try{const x=await api('/records?limit=25',{write:true});records=x.payload.records||[];}catch{}res.send(shell('Issuer Dashboard','Record operations',`<main class="section"><h1>Issuer Dashboard</h1><div class="actions"><a class="btn" href="/issuer/records/new">Issue Record</a><form method="post" action="/issuer/logout"><button>Sign Out</button></form></div><section class="card"><table class="table">${records.map(x=>`<tr><td class="mono">${escapeHtml(x.qrvid)}</td><td>${escapeHtml(x.recordType)}</td><td>${escapeHtml(x.state)}</td><td><a href="/issuer/records/${encodeURIComponent(x.qrvid)}">Open</a></td></tr>`).join('')||'<tr><td>No records returned.</td></tr>'}</table></section></main>`));});
app.get('/issuer/records/new',requireIssuer,(_q,r)=>r.send(shell('Issue Record','Create QR-V record',`<main class="section"><h1>Issue Record</h1><form class="stack" method="post" action="/issuer/records"><select name="recordType"><option>certificate</option><option>membership</option><option>product</option><option>document</option><option>asset</option><option>property</option></select><input name="issuer" required placeholder="Issuer"><input name="owner" placeholder="Recipient / Owner"><input name="title" placeholder="Title"><input type="date" name="expirationDate"><button>Issue QR-V Record</button></form></main>`)));
app.post('/issuer/records',requireIssuer,async(req,res)=>{try{const{response,payload}=await api('/records',{method:'POST',write:true,body:{recordType:req.body.recordType,issuer:req.body.issuer,owner:req.body.owner||null,title:req.body.title||null,expirationDate:req.body.expirationDate||null}});if(!response.ok)return res.status(response.status).send('Issuance failed');res.redirect(303,`/issuer/records/${encodeURIComponent(payload.qrvid)}`);}catch(e){res.status(503).send('Issuance unavailable');}});
app.get('/issuer/records/:qrvid',requireIssuer,async(req,res)=>{const q=String(req.params.qrvid||'').trim().toUpperCase();try{const{response,payload}=await api(`/records/${encodeURIComponent(q)}`);if(!response.ok)return res.status(response.status).send('Record not found');const x=payload.record||{};res.send(shell(`Issuer • ${q}`,'Issuer record',`<main class="section"><h1>${escapeHtml(q)}</h1><section class="grid"><article class="card"><p>${escapeHtml(x.title||x.recordType||'')}</p><p>${escapeHtml(x.state||'')}</p></article><article class="card"><img alt="QR" src="/qr/${encodeURIComponent(q)}.svg" style="max-width:260px;background:white;padding:10px"></article><article class="card">${x.state==='VERIFIED'?`<form method="post" action="/issuer/records/${encodeURIComponent(q)}/revoke"><input name="reason" placeholder="Reason"><button>Revoke</button></form>`:''}</article></section></main>`));}catch{res.status(503).send('Record unavailable');}});
app.post('/issuer/records/:qrvid/revoke',requireIssuer,async(req,res)=>{const q=String(req.params.qrvid||'').trim().toUpperCase();try{const{response}=await api(`/records/${encodeURIComponent(q)}/revoke`,{method:'POST',write:true,body:{reason:req.body.reason||null}});if(!response.ok)return res.status(response.status).send('Revocation failed');res.redirect(303,`/issuer/records/${encodeURIComponent(q)}`);}catch{res.status(503).send('Revocation unavailable');}});
app.get('/qr/:qrvid.svg',async(req,res)=>{const q=String(req.params.qrvid||'').trim().toUpperCase();if(!/^QRV-[A-Z0-9][A-Z0-9-]{2,127}$/.test(q))return res.status(422).send('Invalid QRVID');try{res.type('image/svg+xml').send(await QRCode.toString(`${APP_ORIGIN}/verify/${encodeURIComponent(q)}`,{type:'svg',errorCorrectionLevel:'M',margin:4}));}catch{res.status(500).send('QR generation failed');}});

// Backward-compatible public API gateway. Backend logic still executes only on api.qrv.network.
app.all('/api/v1/*',async(req,res)=>{const target=`${API_ORIGIN}${req.originalUrl}`;try{const headers={accept:req.headers.accept||'application/json','content-type':req.headers['content-type']||'application/json','x-request-id':String(req.headers['x-request-id']||crypto.randomUUID())};const method=req.method.toUpperCase();const options={method,headers,redirect:'manual'};if(!['GET','HEAD'].includes(method)&&req.body&&Object.keys(req.body).length)options.body=JSON.stringify(req.body);const upstream=await fetch(target,options);const body=await upstream.arrayBuffer();res.status(upstream.status);const ct=upstream.headers.get('content-type');if(ct)res.setHeader('content-type',ct);res.setHeader('cache-control',upstream.headers.get('cache-control')||'no-store');return res.send(Buffer.from(body));}catch{return res.status(503).json({ok:false,state:'UNAVAILABLE',error:{code:'API_UNAVAILABLE',message:'Canonical API unavailable'},timestamp:new Date().toISOString()});}});
app.get('/healthz',(_q,r)=>r.json({ok:true,status:'ok',service:SERVICE,version:VERSION,architecture:'two-node-consolidated',frontend:fs.existsSync(WEB_INDEX)?'sites-react':'ssr-fallback',timestamp:new Date().toISOString()}));app.get('/health',(_q,r)=>r.json({ok:true,status:'ok',service:SERVICE,version:VERSION,timestamp:new Date().toISOString()}));app.get('/readyz',async(_q,r)=>{try{const{response,payload}=await apiRoot('/readyz');r.status(response.ok?200:503).json({ok:response.ok,ready:response.ok,service:SERVICE,api:payload});}catch(e){r.status(503).json({ok:false,ready:false,service:SERVICE,error:e.message});}});app.get('/version',(_q,r)=>r.json({ok:true,service:SERVICE,version:VERSION,startedAt:STARTED_AT,platform:APP_ORIGIN,api:API_BASE_URL,frontend:fs.existsSync(WEB_INDEX)?'sites-react':'ssr-fallback'}));
app.get('/site.webmanifest',(_q,r)=>{const manifest=path.join(WEB_DIST,'site.webmanifest');if(fs.existsSync(manifest))return r.type('application/manifest+json').sendFile(manifest);return r.type('application/manifest+json').send({name:'QR-V Global Verification Network',short_name:'QR-V',start_url:'/',display:'standalone',background_color:'#071126',theme_color:'#071126',icons:[]});});
app.get('/robots.txt',(_q,r)=>r.type('text/plain').send('User-agent: *\nAllow: /\nDisallow: /issuer/dashboard\nDisallow: /issuer/records\nDisallow: /admin\nSitemap: https://qrv.network/sitemap.xml\n'));app.get('/sitemap.xml',(_q,r)=>{const p=['/','/network','/protocol','/how-it-works','/standards','/verify','/registry','/use-cases','/developers','/api-reference','/docs','/pricing','/about','/security','/certificate-verification','/enterprise','/status'];r.type('application/xml').send(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${p.map(x=>`<url><loc>${APP_ORIGIN}${x}</loc></url>`).join('')}</urlset>`);});
app.get('/:qrvid(QRV-[A-Za-z0-9-]+)',(req,r)=>r.redirect(308,`/verify/${encodeURIComponent(req.params.qrvid.toUpperCase())}`));app.use((req,r)=>r.status(404).send(page({eyebrow:'QR-V',title:'Page not found',lead:`No route exists for ${req.path}.`})));app.use((e,_q,r,_n)=>{console.error(e);r.status(500).send(page({eyebrow:'QR-V',title:'Platform error',lead:'The request could not be completed.'}));});
app.listen(PORT,'0.0.0.0',()=>{console.log(`${SERVICE} ${VERSION} running on 0.0.0.0:${PORT}`);});
